/* The interface's glyph vocabulary, in one place.

   Every icon in the app is imported from here and nowhere else, under the
   name the call sites already use. The drawing comes from Phosphor: filled
   outlines rather than stroked paths, so a 16px glyph lands on whole device
   pixels without the `non-scaling-stroke` workaround Lucide needed, and its
   rounded terminals sit closer to the system glyphs a Mac draws beside it.
   A glyph changes here, once, and never at a call site. */
export {
  Archive,
  ArrowCounterClockwise as ArchiveRestore,
  SortAscending as ArrowDownAZ,
  ArrowsDownUp as ArrowDownUp,
  ArrowRight,
  ArrowCircleUp as ArrowUpCircle,
  ArrowUpRight,
  At as AtSign,
  TextB as Bold,
  BookOpen,
  Books,
  Article as Chapters,
  TextSuperscript as Footnote,
  CalendarBlank as CalendarDays,
  BookmarkSimple as Bookmark,
  ClockCounterClockwise as History,
  Info,
  Camera,
  Check,
  CaretDown as ChevronDown,
  CaretLeft as ChevronLeft,
  CaretRight as ChevronRight,
  CaretUp as ChevronUp,
  Circle,
  ClipboardText as ClipboardCopy,
  Clock as Clock3,
  Code as Code2,
  SquareSplitHorizontal as Columns2,
  Columns as Columns3,
  Columns as Columns4,
  CircleHalf as Contrast,
  Copy,
  DownloadSimple as Download,
  Eraser,
  ArrowSquareOut as ExternalLink,
  Eye,
  EyeSlash as EyeOff,
  FileArrowDown as FileDown,
  FileText,
  FileArrowUp as FileUp,
  FolderSimple as Folder,
  FolderSimple as FolderDown,
  ArrowBendDownRight as FolderInput,
  FolderOpen,
  FolderSimplePlus as FolderPlus,
  TreeStructure as FolderTree,
  DotsSixVertical as GripVertical,
  TextHOne as Heading1,
  TextHTwo as Heading2,
  TextHThree as Heading3,
  Highlighter,
  Image,
  ImageBroken as ImageOff,
  ImageSquare as ImagePlus,
  TextItalic as Italic,
  Keyboard,
  Stack as Layers,
  LinkSimple as Link,
  Link as Link2,
  ListBullets as List,
  ListChecks,
  ListNumbers as ListOrdered,
  ListDashes as ListTree,
  CircleNotch as Loader2,
  ArrowCounterClockwise as RotateCcw,
  LockSimple as Lock,
  LockSimpleOpen as LockOpen,
  SignOut as LogOut,
  EnvelopeSimple as Mail,
  EnvelopeOpen as MailCheck,
  CornersOut as Maximize2,
  ChatCircle as MessageSquare,
  ChatCircleDots as MessageSquarePlus,
  CornersIn as Minimize2,
  Minus,
  Monitor,
  Moon,
  DotsThree as MoreHorizontal,
  Cursor as MousePointer2,
  ArrowsOutCardinal as Move,
  NotePencil as NotebookPen,
  Notebook as NotebookText,
  PaintBucket,
  Palette,
  SidebarSimple as PanelLeftClose,
  SidebarSimple as PanelLeftOpen,
  Paperclip,
  PencilSimple as Pencil,
  Paragraph as Pilcrow,
  Plus,
  PushPin as Pin,
  Printer,
  Quotes as Quote,
  Rows as Rows3,
  GitDiff as Review,
  MagnifyingGlass as Search,
  GearSix as Settings,
  ShieldCheck,
  TextAUnderline as SpellCheck,
  Square,
  NotePencil as SquarePen,
  TextStrikethrough as Strikethrough,
  Sun,
  Table as Table2,
  Target,
  Timer,
  Trash as Trash2,
  TextT as Type,
  ArrowUUpLeft as Undo2,
  ArrowUUpRight as Redo2,
  TextAlignLeft as AlignLeft,
  TextAlignCenter as AlignCenter,
  TextAlignRight as AlignRight,
  TextAlignJustify as AlignJustify,
  TextUnderline as Underline,
  TextSubscript as Subscript,
  TextSuperscript as Superscript,
  TextIndent as Indent,
  TextOutdent as Outdent,
  FileDashed as PageBreak,
  ArrowsVertical as LineSpacing,
  Ruler,
  Export,
  SidebarSimple as PanelRight,
  TreeView as Structure,
  UploadSimple as Upload,
  UserPlus,
  User as UserRound,
  Users,
  MagicWand as Wand2,
  X,
  MagnifyingGlassPlus as ZoomIn,
} from "@phosphor-icons/react";
